---
- hosts: all
  become: true
  vars:
    container_count: 1
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
    
    - name: Install required sysytem packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-propertlies-common
          - puthon3-setuptools
        state: latest
        apdate_cache: true

    - name: Add Docker GPG apt Key 
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present 

    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: update apt and instal docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: install docker module for py
      pip:
        name: docker

    - name: pull defaul dockerimage
      community.docker.docker_image:
        name: "{ default_container_image }"
        source: pull

    - name: create default containers
      community.docker.docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ container_count }}

          





























