---
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
  become: true

- name: Ensure PHP and PHP-FPM are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php-fpm
    - php-mysql
    - php-cli
  become: true

- name: Create document root
  file:
    path: /opt/nginx/ansible
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Create index.php
  copy:
    content: "<?php phpinfo(); ?>"
    dest: /opt/nginx/ansible/index.php
    owner: www-data
    group: www-data
    mode: '0644'
  become: true

- name: Configure Nginx to use PHP processor
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - Reload Nginx
  become: true

- name: Ensure PHP-FPM is started and enabled
  service:
    name: php7.4-fpm
    state: started
    enabled: yes
  become: true

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
  become: true

